---
# tasks file for ansible-role-regenerate_ssh_host_keys

- name: Include OS-specific variables.
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: Define rhk_ssh_service_name.
  set_fact:
    rhk_ssh_service_name: "{{ __rhk_ssh_service_name }}"
  when: rhk_ssh_service_name is not defined

- name: Deploy service file.
  template:
    src: 'etc/systemd/system/ansible-regenerate_ssh_host_keys.service.j2'
    dest: '/etc/systemd/system/ansible-regenerate_ssh_host_keys.service'
    owner: root
    group: root
    mode: 0644

- name: Ensure the regenerate_ssh_host_keys service is enabled.
  ansible.builtin.systemd:
    name: ansible-regenerate_ssh_host_keys.service
    enabled: true
    daemon_reload: true
